version: "3.7"

services:
  example_docker_shiny:
    image: jsleight1/example_docker_shiny:R4.4.2-latest
    restart: unless-stopped
  lgbf:
    image: jsleight1/lgbf:R4.4.2-latest
    restart: unless-stopped
  example_database_shiny:
    image: jsleight1/example_database_shiny:R4.4.2-latest
    restart: unless-stopped
    volumes:
     - $dbpath:/home/app/data
  caddy:
    image: caddy:2.3.0-alpine
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - example_docker_shiny
      - lgbf
      - example_database_shiny

volumes:
  caddy_data:
  caddy_config:

